### PR TITLE
adding croatian translations (iso hr)

### PR DESCRIPTION
**Pull request by ak-42**
Hi
Here's my Croatian translation. Please note that the capitalisation rules are a bit different in Croatian, and strings out of context are hard to capitalise correctly, there could be some capitalisation errors. If you merge the pull, I'll have a look in context and probably suggest capitalisation changes.

Also, I'm kinda new to git(hub), so sorry I messed something up. If I did I can also just send you the .csv directly.

### CODE REVIEW

**Comment by bumbeishvili** [comment]
I just took a look

Screen Shot 2020-03-28 at 15 39 10

It looks like Serbian and Croatian have similar words, are they same language? 

I have another setting in place, where I can default different languages to different countries.

So, people in Argentina will see Spanish as a default language.
Let me know if this is a case for Serbian and Croatian language and I will set those defaults.

I worry because the translation file is getting bigger in size and don't want to increase the load on the user

**Comment by ak-42** [comment]
Uh... now you've stepped into centuries of politics. This is like Israeli vs Palistinian conflict, but older and more deep rooted.
They are closely related languages. Many linguists will say that Serbian and Croatian are the same language (Serbo-Croatian), but both Serbs and Croatians have literally died over claims of difference. See Croatian War of Independence.

You can, if necessary, enable Serbian for entire area of former Yugoslavia, but by god please at least call it Serbo-Croatian which is the internationally accepted term encompassing all variants of the most dominant language of Former Yugoslavia. The problem is that it does not have an iso code and, if you care about such things, neither Serbs nor Croats will be happy about it.

Edit: Might also be worth noting that Croatian vs Serbian differences are more apparent in more complex speech or text, while these strings are pretty basic and basic words often have common Slavic roots.

**Comment by bumbeishvili** [comment]
Interesting, I think for now I will merge this request, but if other people make PR's for former Yugoslavia countries, I will think about other ways

**Comment by ak-42** [comment]
You can also enable either Croatian or Serbian (best you choose, as a neutral party) for Bosnia and Herzegovina and Serbian for Montenegro and Kosovo.
Do not enable anything for North Macedonia or Slovenia, probably best to just leave English.

**Comment by bumbeishvili** [comment]
Thank you, will do that right away

**Pull request merged**
